name: glider_dvl_analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - xarray
  - scipy
  - h5netcdf
  - matplotlib
  - plotly
  - ruff
  - pip:
    - python-dotenv
    - mkdocs
    - -e .